#!/bin/bash
# Simple script to run validation in the correct environment

echo "================================================================"
echo "FEVER Dataset Loading - Alternative Approach"
echo "================================================================"
echo ""
echo "The validation showed that:"
echo "  ✓ All code imports work correctly"
echo "  ✓ P1 Protocol is properly configured"
echo "  ✗ FEVER dataset needs an alternative source"
echo ""
echo "I've updated the code to try multiple FEVER sources:"
echo "  1. lucadiliello/FEVER (processed version)"
echo "  2. Original FEVER dataset"
echo "  3. Mock data fallback (for testing)"
echo ""
echo "To run validation with your virtual environment:"
echo ""
echo "  source /path/to/your/cheaptalk/venv/bin/activate"
echo "  python validate_setup.py"
echo ""
echo "Or if using conda:"
echo ""
echo "  conda activate cheaptalk"
echo "  python validate_setup.py"
echo ""
echo "================================================================"
